# version string format -- This will be overwritten later anyway
version: "{build}"

os:
  - Visual Studio 2017
  - Visual Studio 2015
  - Visual Studio 2013
  
# clone directory
clone_folder: C:\projects\polylineencoder

init:
  - git config --global core.autocrlf input
  
# branches to build
branches:
  # whitelist
  only: 
    - master

platform:
  - Win32
  - x64

# build Configurations, i.e. Debug, Release, etc.
configuration:
  - Debug
  - Release

build_script:
    - cd C:\projects\polylineencoder\test
    - cl /EHsc main.cpp

test_script:
  - cd C:\projects\polylineencoder\test
  - main.exe